package com.example.study.dao;

import com.example.study.dataobject.Temporary;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TemporaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    @Delete({
        "delete from temporary",
        "where openid = #{openid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    @Insert({
        "insert into temporary (openid, longitude, ",
        "latitude)",
        "values (#{openid,jdbcType=VARCHAR}, #{longitude,jdbcType=VARCHAR}, ",
        "#{latitude,jdbcType=VARCHAR})"
    })
    int insert(Temporary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    @Select({
        "select",
        "openid, longitude, latitude",
        "from temporary",
        "where openid = #{openid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="longitude", property="longitude", jdbcType=JdbcType.VARCHAR),
        @Result(column="latitude", property="latitude", jdbcType=JdbcType.VARCHAR)
    })
    Temporary selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    @Select({
        "select",
        "openid, longitude, latitude",
        "from temporary"
    })
    @Results({
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="longitude", property="longitude", jdbcType=JdbcType.VARCHAR),
        @Result(column="latitude", property="latitude", jdbcType=JdbcType.VARCHAR)
    })
    List<Temporary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    @Update({
        "update temporary",
        "set longitude = #{longitude,jdbcType=VARCHAR},",
          "latitude = #{latitude,jdbcType=VARCHAR}",
        "where openid = #{openid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Temporary record);
}