package com.example.study.dataobject;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.receiver_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private Integer receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.openid
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.route_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private Integer routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.organization_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private Long organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.event_address
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private String eventAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.event_longitude
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private String eventLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.event_latitude
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private String eventLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.event_location
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private String eventLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.number_people
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private Byte numberPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.type
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.receiver_id
     *
     * @return the value of task.receiver_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.receiver_id
     *
     * @param receiverId the value for task.receiver_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.openid
     *
     * @return the value of task.openid
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.openid
     *
     * @param openid the value for task.openid
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.route_id
     *
     * @return the value of task.route_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.route_id
     *
     * @param routeId the value for task.route_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.organization_id
     *
     * @return the value of task.organization_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.organization_id
     *
     * @param organizationId the value for task.organization_id
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.event_address
     *
     * @return the value of task.event_address
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public String getEventAddress() {
        return eventAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.event_address
     *
     * @param eventAddress the value for task.event_address
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setEventAddress(String eventAddress) {
        this.eventAddress = eventAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.event_longitude
     *
     * @return the value of task.event_longitude
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public String getEventLongitude() {
        return eventLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.event_longitude
     *
     * @param eventLongitude the value for task.event_longitude
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setEventLongitude(String eventLongitude) {
        this.eventLongitude = eventLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.event_latitude
     *
     * @return the value of task.event_latitude
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public String getEventLatitude() {
        return eventLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.event_latitude
     *
     * @param eventLatitude the value for task.event_latitude
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setEventLatitude(String eventLatitude) {
        this.eventLatitude = eventLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.event_location
     *
     * @return the value of task.event_location
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public String getEventLocation() {
        return eventLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.event_location
     *
     * @param eventLocation the value for task.event_location
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setEventLocation(String eventLocation) {
        this.eventLocation = eventLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.number_people
     *
     * @return the value of task.number_people
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public Byte getNumberPeople() {
        return numberPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.number_people
     *
     * @param numberPeople the value for task.number_people
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setNumberPeople(Byte numberPeople) {
        this.numberPeople = numberPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.type
     *
     * @return the value of task.type
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.type
     *
     * @param type the value for task.type
     *
     * @mbg.generated Fri Feb 15 00:15:34 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }
}