package com.example.study.dataobject;

public class Worker {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.openid
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.tel
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.is_task
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    private Byte isTask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.job
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.name
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.task_id
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.organization_id
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    private Long organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.image
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.openid
     *
     * @return the value of worker.openid
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.openid
     *
     * @param openid the value for worker.openid
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.tel
     *
     * @return the value of worker.tel
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.tel
     *
     * @param tel the value for worker.tel
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.is_task
     *
     * @return the value of worker.is_task
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public Byte getIsTask() {
        return isTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.is_task
     *
     * @param isTask the value for worker.is_task
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public void setIsTask(Byte isTask) {
        this.isTask = isTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.job
     *
     * @return the value of worker.job
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.job
     *
     * @param job the value for worker.job
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.name
     *
     * @return the value of worker.name
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.name
     *
     * @param name the value for worker.name
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.task_id
     *
     * @return the value of worker.task_id
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.task_id
     *
     * @param taskId the value for worker.task_id
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.organization_id
     *
     * @return the value of worker.organization_id
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.organization_id
     *
     * @param organizationId the value for worker.organization_id
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.image
     *
     * @return the value of worker.image
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.image
     *
     * @param image the value for worker.image
     *
     * @mbg.generated Fri Feb 15 00:03:24 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }
}