package com.example.study.dao;

import com.example.study.dataobject.User;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    @Delete({
        "delete from user",
        "where openid = #{openid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    @Insert({
        "insert into user (openid, session_key, ",
        "tel, task_id, is_task, ",
        "name, id, image)",
        "values (#{openid,jdbcType=VARCHAR}, #{sessionKey,jdbcType=VARCHAR}, ",
        "#{tel,jdbcType=VARCHAR}, #{taskId,jdbcType=INTEGER}, #{isTask,jdbcType=TINYINT}, ",
        "#{name,jdbcType=VARCHAR}, #{id,jdbcType=VARCHAR}, #{image,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    @Select({
        "select",
        "openid, session_key, tel, task_id, is_task, name, id, image",
        "from user",
        "where openid = #{openid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="session_key", property="sessionKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="tel", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="task_id", property="taskId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_task", property="isTask", jdbcType=JdbcType.TINYINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR)
    })
    User selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    @Select({
        "select",
        "openid, session_key, tel, task_id, is_task, name, id, image",
        "from user"
    })
    @Results({
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="session_key", property="sessionKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="tel", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="task_id", property="taskId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_task", property="isTask", jdbcType=JdbcType.TINYINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR)
    })
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    @Update({
        "update user",
        "set session_key = #{sessionKey,jdbcType=VARCHAR},",
          "tel = #{tel,jdbcType=VARCHAR},",
          "task_id = #{taskId,jdbcType=INTEGER},",
          "is_task = #{isTask,jdbcType=TINYINT},",
          "name = #{name,jdbcType=VARCHAR},",
          "id = #{id,jdbcType=VARCHAR},",
          "image = #{image,jdbcType=VARCHAR}",
        "where openid = #{openid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(User record);
}