package com.example.study.dataobject;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization_id
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    private Long organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    private String organization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.longitude
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.latitude
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.address
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.tel
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization_id
     *
     * @return the value of organization.organization_id
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization_id
     *
     * @param organizationId the value for organization.organization_id
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization
     *
     * @return the value of organization.organization
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization
     *
     * @param organization the value for organization.organization
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public void setOrganization(String organization) {
        this.organization = organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.longitude
     *
     * @return the value of organization.longitude
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.longitude
     *
     * @param longitude the value for organization.longitude
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.latitude
     *
     * @return the value of organization.latitude
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.latitude
     *
     * @param latitude the value for organization.latitude
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.address
     *
     * @return the value of organization.address
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.address
     *
     * @param address the value for organization.address
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.tel
     *
     * @return the value of organization.tel
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.tel
     *
     * @param tel the value for organization.tel
     *
     * @mbg.generated Fri Feb 15 00:02:11 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }
}