package com.example.study.dataobject;

public class Temporary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temporary.openid
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temporary.longitude
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temporary.latitude
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    private String latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temporary.openid
     *
     * @return the value of temporary.openid
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temporary.openid
     *
     * @param openid the value for temporary.openid
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temporary.longitude
     *
     * @return the value of temporary.longitude
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temporary.longitude
     *
     * @param longitude the value for temporary.longitude
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temporary.latitude
     *
     * @return the value of temporary.latitude
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temporary.latitude
     *
     * @param latitude the value for temporary.latitude
     *
     * @mbg.generated Fri Mar 15 18:16:19 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
}