package com.example.study.dataobject;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.openid
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.session_key
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    private String sessionKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tel
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.task_id
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_task
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    private Byte isTask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.image
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.openid
     *
     * @return the value of user.openid
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.openid
     *
     * @param openid the value for user.openid
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.session_key
     *
     * @return the value of user.session_key
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.session_key
     *
     * @param sessionKey the value for user.session_key
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tel
     *
     * @return the value of user.tel
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tel
     *
     * @param tel the value for user.tel
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.task_id
     *
     * @return the value of user.task_id
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.task_id
     *
     * @param taskId the value for user.task_id
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_task
     *
     * @return the value of user.is_task
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public Byte getIsTask() {
        return isTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_task
     *
     * @param isTask the value for user.is_task
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public void setIsTask(Byte isTask) {
        this.isTask = isTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.image
     *
     * @return the value of user.image
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.image
     *
     * @param image the value for user.image
     *
     * @mbg.generated Fri Feb 15 00:03:56 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }
}